image: ubuntu

stages:
  - build
  - test


compile_cmake:
  stage: build

  script:
    - apt-get update -qq
    - apt-get install -y -qq build-essential pkg-config bison flex  autoconf automake libtool make cmake sqlite3
    - mkdir build
    - cd build
    - cmake ../
    - make



pages:
  script:
  - apt-get update -qq
  - apt-get install -y -qq doxygen graphviz
  - doxygen ./etc/docs/doxygen.conf
  artifacts:
    paths:
    - public
  only:
  - build_stuff
